/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PickupRouteImport } from './routes/pickup'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SkillCentersRouteImport } from './routes/skill-centers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupRoute = PickupRouteImport.update({
  id: '/pickup',
  path: '/pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillCentersRoute = SkillCentersRouteImport.update({
  id: '/skill-centers',
  path: '/skill-centers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/dashboard': typeof DashboardRoute
  '/pickup': typeof PickupRoute
  '/scan': typeof ScanRoute
  '/signin': typeof SigninRoute
  '/skill-centers': typeof SkillCentersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/dashboard': typeof DashboardRoute
  '/pickup': typeof PickupRoute
  '/scan': typeof ScanRoute
  '/signin': typeof SigninRoute
  '/skill-centers': typeof SkillCentersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/dashboard': typeof DashboardRoute
  '/pickup': typeof PickupRoute
  '/scan': typeof ScanRoute
  '/signin': typeof SigninRoute
  '/skill-centers': typeof SkillCentersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/careers'
    | '/dashboard'
    | '/pickup'
    | '/scan'
    | '/signin'
    | '/skill-centers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/careers'
    | '/dashboard'
    | '/pickup'
    | '/scan'
    | '/signin'
    | '/skill-centers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/careers'
    | '/dashboard'
    | '/pickup'
    | '/scan'
    | '/signin'
    | '/skill-centers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CareersRoute: typeof CareersRoute
  DashboardRoute: typeof DashboardRoute
  PickupRoute: typeof PickupRoute
  ScanRoute: typeof ScanRoute
  SigninRoute: typeof SigninRoute
  SkillCentersRoute: typeof SkillCentersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup': {
      id: '/pickup'
      path: '/pickup'
      fullPath: '/pickup'
      preLoaderRoute: typeof PickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-centers': {
      id: '/skill-centers'
      path: '/skill-centers'
      fullPath: '/skill-centers'
      preLoaderRoute: typeof SkillCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CareersRoute: CareersRoute,
  DashboardRoute: DashboardRoute,
  PickupRoute: PickupRoute,
  ScanRoute: ScanRoute,
  SigninRoute: SigninRoute,
  SkillCentersRoute: SkillCentersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
